### ISSUE TITLE
fix(genesis): preview cnight-config.json zeroed and diverged from its chainspec

### ISSUE THREAD

**Issue by gilescope** [midnightntwrk/midnight-node#1949]
`res/preview/cnight-config.json` is zeroed (anchor block 0, no UTXOs, `system_tx: null`) but the committed `res/preview/chain-spec.json` anchors at Cardano preview **4099440** with 1904 UTXOs / 435 mappings / a `system_tx`. `res/cfg/preview.toml:10` feeds that config into chainspec generation, so `earthly -P +rebuild-chainspec --NETWORK=preview` would silently emit a block-0 anchor and drop the genesis UTXOs — preview would then replay cNIGHT observation from the dawn of Cardano preview.

Preview is the only network where the two disagree (preprod 4500197, mainnet 13164005, qanet/devnet/govnet/perfnet all match their chainspecs).

Evidence it's a generation gap, not intent:

- Every other network's `observed_utxos.end.block_hash` equals its `cardano-tip.json`. Preview's tip file says `0xda76a13c…`; the config holds the zero hash.
- Tip file refreshed in #1282; the config untouched since #631.
- The config carries `redemption_validator_address`, a key `CNightAddresses` doesn't define — silently dropped, and absent from the chainspec's embedded `addresses`. So the shipped chainspec was built from a different input than the file in the repo.

Already broken today: `genesis-verification.sh:345` can't pass for preview, and `--cnight-config res/preview/cnight-config.json` reports "DustState correctly empty" (`verify_ledger_state_genesis.rs:320`) while genesis has a `system_tx`.

**Fix:** regenerate `res/preview/cnight-config.json` against the anchor already in the chainspec (4099440, `0xd6460b26588e984355a8c5c6007301084aaab10f95f57ab39a9f3d5f52af4b5b`); add a CI check that each network's `cnight-config.json`, `chain-spec.json` and `cardano-tip.json` agree.

**Verify**

- [ ] `next_cardano_position` / `observed_utxos` identical between `res/preview/cnight-config.json` and `res/preview/chain-spec.json`
- [ ] config `observed_utxos.end.block_hash` == `cardano-tip.json` `cardano_tip`, as for every other network
- [ ] `redemption_validator_address` gone
- [ ] `earthly -P +rebuild-chainspec --NETWORK=preview` yields no diff against the committed chainspec
- [ ] New CI check fails when the three files disagree

Not "0 is intentional" — per Slack the anchors were per-network convenience, but preview's zero contradicts its own `cardano-tip.json` and chainspec. Not `deny_unknown_fields` on `CNightAddresses` as the fix (worth doing separately; wouldn't have caught the zeroed anchor).

Reported by marek.mahut in Slack; anchor history from Justin Frevert.

**Comment by gilescope** [comment]
Confirmed still open on HEAD (e8c407d9). `res/preview/cnight-config.json` is all-zeros while `res/preview/chain-spec.json` embeds block 4099440 with real UTXOs - the divergence was introduced in PR #1282, which upstreamed the 0.22.3 release chain-specs but omitted `cnight-config.json` for preview (it did update mainnet's equivalent).

The `redemption_validator_address` field in the config is silently dropped at load time - `CNightAddresses` (`primitives/cnight-observation/src/lib.rs:174`) has no such field - confirming the file was written against an older struct.

No commits since 2026-07-29 have touched `res/preview/cnight-config.json`. The remote branch `justin-regenerate-preview-0.22.3` (PR #1071, March 2026) is stale and based on old main; it did not update the cnight-config either.

No CI consistency check exists between `cnight-config.json`, `chain-spec.json`, and `cardano-tip.json`.

Next action: @justinfrevert - please regenerate `res/preview/cnight-config.json` via `generate-c-night-genesis` anchored at block 4099440 (`0xd6460b26...`) and add the CI check proposed in the issue description.

---
*Claude triage review - an automated pass over open bugs with little recent activity. Conclusions come from reading this issue plus the current code and git history, and may be wrong; please correct anything that is off.*
